openapi: 3.0.0
info:
  title: e-commerce api definition
  description: API Definition
  version: 1.0.0
servers:
  - url: http://192.168.83.132:6078
    description: Admin Service
  - url: http://192.168.83.132:6088
    description: Product Service
security:
  - default: []
paths:
  /api/auth/signup:
    post:
      summary: Register a new admin
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminRegistration'
      responses:
        '201':
          description: Admin registered successfully
        '400':
          description: Bad Request. Invalid request or validation error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
  /api/auth/signin:
    post:
      summary: Admin login and token generation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdminLogin'
      responses:
        '200':
          description: Admin logged in successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        '401':
          description: Unauthorized. Invalid credentials.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
  /api/products:
    get:
      summary: Get a list of products
      responses:
        '200':
          description: OK. List of products is returned.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '401':
          description: Unauthorized. Token is missing or invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
components:
  schemas:
    AdminRegistration:
      title: Admin registration request
      required:
        - username
        - password
        - role
      properties:
        username:
          type: string
        password:
          type: string
        role:
          type: array  # Ubah type menjadi array
          items:
            type: string
    AdminLogin:
      title: Admin login request
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    TokenResponse:
      title: Token response
      required:
        - token
      properties:
        token:
          type: string
    Product:
      title: Product
      required:
        - name
        - price
      properties:
        name:
          type: string
        price:
          type: number
    BadRequestError:
      title: Bad Request Error
      properties:
        message:
          type: string
    UnauthorizedError:
      title: Unauthorized Error
      properties:
        message:
          type: string
